version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.Frontend.Dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/
    restart: always
  backend:
    build:
      context: .
      dockerfile: Dockerfile.Backend.Dev
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/web/
    env_file:
      - .env
    restart: always
