name: Deploy to GCP Cloud Run

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker europe-central2-docker.pkg.dev

      - name: Build and Push Backend Image
        run: |
          docker build -f Dockerfile.Backend.Prod -t europe-central2-docker.pkg.dev/resume-analyser-450115/resume-analyser/backend:latest .
          docker push europe-central2-docker.pkg.dev/resume-analyser-450115/resume-analyser/backend:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -f Dockerfile.Frontend.Prod -t europe-central2-docker.pkg.dev/resume-analyser-450115/resume-analyser/frontend:latest .
          docker push europe-central2-docker.pkg.dev/resume-analyser-450115/resume-analyser/frontend:latest

      - name: Deploy Backend to Cloud Run
        run: |
          gcloud run deploy backend \
              --image europe-central2-docker.pkg.dev/resume-analyser-450115/resume-analyser/backend:latest \
              --platform managed  --region europe-central2 --allow-unauthenticated \
              --port=8080

      - name: Set Backend IAM Policy
        run: |
          gcloud beta run services add-iam-policy-binding backend \
              --region=europe-central2 \
              --member=allUsers \
              --role=roles/run.invoker

      - name: Deploy Frontend to Cloud Run
        run: |
          gcloud run deploy frontend \
              --image europe-central2-docker.pkg.dev/resume-analyser-450115/resume-analyser/frontend:latest \
              --platform managed  --region europe-central2 --allow-unauthenticated \
              --port=3000

      - name: Set Frontend IAM Policy
        run: |
          gcloud beta run services add-iam-policy-binding frontend \
              --region=europe-central2 \
              --member=allUsers \
              --role=roles/run.invoker
